version: '3.8'

services:
  # MySQL Database Service
  mysqldb:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: storage_gestion
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Spring Boot Application Service
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      # We point the URL to the container name 'mysqldb' instead of localhost
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/my_app_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: NAMI
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge